name: Update README cards

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Generate stats card dark
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&theme=dracula&include_all_commits=true
          path: profile/stats-dark.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate stats card light
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&theme=default&include_all_commits=true
          path: profile/stats-light.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate top languages card dark
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&layout=compact&theme=dracula&langs_count=6
          path: profile/top-langs-dark.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate top languages card light
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&layout=compact&theme=default&langs_count=6
          path: profile/top-langs-light.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate streak
        run: |
          set -xe
          curl -fSsL -Oprofile/streak-dark.svg 'https://github-readme-streak-stats-eight.vercel.app/?theme=dracula&user=${{ github.repository_owner }}'
          curl -fSsL -Oprofile/streak-light.svg 'https://github-readme-streak-stats-eight.vercel.app/?theme=default&user=${{ github.repository_owner }}'

      - name: Commit cards
        run: |
          set -xe
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "Update README cards"
          git push
